name: GitHub-Profile-3D-Contrib
on:
  schedule: [{cron: "59 23 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      # - uses: actions/checkout@v3
      - uses: actions/checkout@v2
      # - uses: yoshi389111/github-profile-3d-contrib@latest
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 250

      - name: Print env ❓
        run: env | sort
      - name: Commit & Push
        run: |
          git config user.name ${{ github.repository_owner }}
          git config user.email xgqfrms@xgqfrms.xyz
          git add -A .
          git commit -m "feat: update GitHub 3D Profile"
          git push
